version: '3.8'

services:
  leader:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    command: python -u server.py
    ports:
      - "5000:5000"
    environment:
      - SLAVE_HOST=follower-1
      - SLAVE_PORT=6000
    networks:
      - minesweeper-net

  follower-1:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    command: python -u slave.py
    ports:
      - "6000:6000"
    environment:
      - NEXT_REPLICA_HOST=follower-2
      - NEXT_REPLICA_PORT=7000
    networks:
      - minesweeper-net

  follower-2:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    command: python -u slave.py
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
    networks:
      - minesweeper-net

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    depends_on:
      - leader
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - minesweeper-net

networks:
  minesweeper-net:
    driver: bridge
